services:
  drivermanagement:
    container_name: drivermanagment
    image: drivermanagement:latest # builds latest driver management image
    ports:
      - "7500:8080" # maps host 7500 to container 8080 port
    environment:
      ASPNETCORE_URLS: "http://+:8080" # tells Kestrel to listen on port 8080 on all network interfaces
      ASPNETCORE_HTTP_PORTS: "8080" #use port 8080
      ASPNETCORE_ENVIRONMENT: "Development"  # set environment to development (can change to prod) 
