# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore CSCN73030_GooberDriverManager.sln
    - name: Build
      run: dotnet build CSCN73030_GooberDriverManager.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test GooberDriverTests/GooberDriverTests.csproj --verbosity normal
